#!/usr/bin/env bash

on boot mantle-bootstrap
on setup mantle-setup

on boot doco-delegate imposer
on boot doco-delegate composer
on boot doco-delegate wp
on boot doco-delegate dba

doco-delegate() {
	# Route in-container commands via docker-compose
	have "$1" || catbin "$1" <<-EOF
	#!/usr/bin/env bash
	exec doco $1 "\$@"
	EOF
}

mantle-bootstrap() {
	require-any doco github bashup/doco master bin/doco
	require dotenv github bashup/dotenv master dotenv
	require-any jq
	require-any docker-compose
	mkdir -p deploy
}

mantle-setup() {
	if [[ ! -f .env ]]; then
		cp share/example.env .env
		echo ".env file created -- you may wish to edit it"
		echo
	fi

	REPLY=(*.doco.md)
	if [[ $REPLY == "*.doco.md" ]]; then
		realpath.basename "$PWD"
		cp share/sample-config.md "$REPLY".doco.md
		echo -n "$REPLY.doco.md configuration file created: "
		echo -n "Edit it to define your sites (and rename if you wish, as long "
		echo "as it retains the .doco.md suffix)."
	fi
} >&2;
